name: Lighthouse Deploy Previews

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for deploy
      uses: maddox/actions/wait-for-200@master
      env:
        URL: 'https://deploy-preview-${{ github.event.pull_request.number }}--chez-nicole.netlify.com/'
        SECONDS_BETWEEN_CHECKS: 20
        MAX_TRIES: 30
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.chez-nicole.fr'
        netlify_site: 'chez-nicole.netlify.com'
    - name: Upload report to Zeit
      run: now -t ${{ secrets.ZEIT_TOKEN }} deploy ./report/https*.html | tee zeit-now.log
    - name: Link to report
      run: |
        TARGET_URL=`tail -n1 zeit-now.log`
        echo "${TARGET_URL}"
    - name: Update status to success
      run: |
        curl -X POST https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{
            \"state\": \"success\",
            \"target_url\": \"${TARGET_URL}\",
            \"description\": \"Lighthouse report\",
            \"context\": \"lighthouse-report\"
          }"
